# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c55334b3fb6d8b2866d22f135a258cf115917300703930ec0e4e57867ba3c0e17665d984b75742c45ca16c03b4fca25d52bc94b17c6360a677214149f4df1969

test:
  secret_key_base: e1a8430aea79df932ffce54a43b203eda1dab2130e854eb9e168b452624aec4a5ac4923c68d19db6c980f5f5ca2d637f3f9beb3e6c4b1382ecd0e87adbf14576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
